use_frameworks!

#target 'PickZyShoppingApp' do
#
#    pod 'RxSwift'
#    pod 'RxCocoa'
#
#    pod 'GoogleMaps'
#    pod 'GooglePlaces'
#    pod 'GooglePlacePicker'
##    pod 'EasyTipView', '~> 1.0.2'
#    pod 'SwiftTheme'
#    pod 'SSZipArchive'
#    pod 'MBProgressHUD'
#    pod 'Alamofire'
#    #    pod 'MXSegmentedPager'
#    pod 'IQKeyboardManagerSwift'
#    pod "QBImagePickerController"
#    pod 'JSONWebToken'
#    pod "CryptoSwift"
#    pod 'SDWebImage', '~> 4.0'
#
#end

def shared_pods

pod 'RxSwift', '~> 4.2.0'
pod 'RxCocoa'

pod 'GoogleMaps', '= 3.0.3'
pod 'GooglePlaces', '= 3.0.3'
pod 'GooglePlacePicker', '= 3.0.3'
pod 'MKToolTip'
#pod 'SwiftTheme'
#pod 'SSZipArchive'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Alamofire', '~> 4.7.3'
pod 'IQKeyboardManagerSwift'
pod "QBImagePickerController"
#pod 'JSONWebToken'
pod "CryptoSwift", '~> 0.11.0'
pod 'SDWebImage', '~> 4.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'GLScratchCard'
pod 'razorpay-pod'


end

platform :ios, '11.0'

target 'Shopor-dev' do
    shared_pods
end
target 'Shopor-qa' do
    shared_pods
end
target 'Shopor' do
    shared_pods
end

